name: ipyrun-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pytest
  - jupyterlab
  - jupytext
  - jupyterlab-lsp
  - python-lsp-server
  - black
  - nb_black
  - halo
  - voila
  - emoji
  - plotly # for example: TODO: change to vega
  - jupyter-dash # for example: TODO: change to vega
  - pip
  - pip:
    - seedir
    - dirty-equals
    - ipyautoui>=0.7.1