name: ipyrun-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - jupytext
  - jupyterlab-lsp
  - python-lsp-server
  - nb_black
  - halo
  - traitlets
  - voila
  - pip
  - pip:
    - traitlets-paths
    - seedir
    - git+https://git@github.com/maxfordham/ipyautoui@main
