name: ipyrun-dev
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - halo
  - jupytext
  - jupyterlab-lsp
  - python-lsp-server
  - black
  - nb_black
  - traitlets
  - voila
  - pip
  - pip:
    - traitlets-paths
    - seedir
    - ipyautoui>=0.5.0
