# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ipyrun
author: mfcode
logo: images/icon.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jgunstone/ipyrun  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: images/icon.ico


sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.todo'
  - 'sphinx.ext.autosummary'
  - 'autoapi.extension'
  config:
    # add_module_names: False
    # autosummary_generate: True
    # autoapi
    autoapi_generate_api_docs: True
    autoapi_add_toctree_entry: True
    autoapi_dirs: ['../src']
    # napoleon
    napoleon_google_docstring: True
    napoleon_numpy_docstring:  False
    napoleon_include_init_with_doc:  False
    napoleon_include_private_with_doc:  False
    napoleon_include_special_with_doc:  True
    napoleon_use_admonition_for_examples:  False
    napoleon_use_admonition_for_notes:  False
    napoleon_use_admonition_for_references:  False
    napoleon_use_ivar:  True
    napoleon_use_param:  True
    napoleon_use_rtype:  True
    # show __init__ docstring
    # https://stackoverflow.com/questions/5599254/how-to-use-sphinxs-autodoc-to-document-a-classs-init-self-method
    autoclass_content:  both
    # html_static_path: ['_static']