name: ipyrun-docs
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
# -
# jg notes
# - 
# - needs everything that ipyautoui needs + everything for docs
# - in future when packaged could make ipyautoui a dependency
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7,<3.10
  - numpy
  - pandas
  - matplotlib
  - jupyterlab>=3.0.14
  - voila>=0.2.11
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - pyyaml
  - pillow
  - openpyxl
  - black
  - nb_black
  - immutables
  - stringcase
  - emoji
  - jupyter-book # for docs
  - sphinx # for docs
  - sphinx-book-theme # for docs
  - sphinx-autoapi
  - nbsphinx-link
  - autodoc-pydantic # for docs
  - pytest
  - pip
  - pip:
    - traitlets-paths
    - seedir
    - git+https://git@github.com/maxfordham/ipyautoui@main
