name: ipyrun
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - jupyterlab
  - xeus-python
  - ipywidgets
  - ipysheet
  - ipyfilechooser
  - voila
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - dacite
  - xmltodict
  - pyyaml
  - pillow
  - pip
  - click
  - openpyxl
  - xlsxwriter 
  #- xlsxtemplater 
  #- mf_file_utilities 
  - mfom
