name: ipyrun
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - conda-forge
  - http://10.10.30.125:8000
dependencies:
  - python>=3.7
  - numpy
  - pandas
  - jupyterlab==3.0.14
  - xeus-python
  - ipywidgets
  - ipysheet
  - ipyfilechooser
  - voila
  - plotly
  - halo
  - jupytext
  - markdown
  - nodejs
  - altair
  - pydantic
  - dacite
  - xmltodict
  - pyyaml
  - pillow
  - pip
  - click
  - openpyxl
  - xlsxwriter 
  - xlsxtemplater 
  - mf_file_utilities 
  - mfom
