{% set data = load_setup_py_data() %}

package:
  name: ipyrun
  version: {{ data['version'] }}

source:
  path: ..

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt #{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .
  entry_points:
    - processrcmfolder = uconnrcmpy.dataprocessing:process_folder
 
requirements:

  host:
    - python
    - numpy
    
  run:
    - python
    - numpy
    - pandas
    - click
    - dataclasses
    - typing
    - dacite
    - pydantic
    - xmltodict
    - plotly
    - xlsxwriter
    - markdown
    - ipython
    - ipysheet
    - ipyfilechooser
    - ipyaggrid
    - halo
    - mffileutilites # mf package
    - xlsxtemplater # mf package
    # dependencies are defined in setup.py
    # {% for dep in data['install_requires'] %}
    # - {{ dep.lower() }}
    # {% endfor %}

about:
  home: https://github.com/gunstonej/ipyrun
  summary: {{ data.get('description') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
